export default {
    BUSINESS_PLAN_POST_REQUEST:"BUSINESS_PLAN_POST_REQUEST",
    BUSINESS_PLAN_POST_REQUEST_SUCCESS:"BUSINESS_PLAN_POST_REQUEST_SUCCESS",
    BUSINESS_PLAN_POST_REQUEST_ERROR:"BUSINESS_PLAN_POST_REQUEST_ERROR",

    CLEAR_STORE:"BUSINESS_PLAN_POST_REQUEST_ERROR",
}